Add description method to NSObject
nvzqz/fruity pull request #8
Opened 2020-12-30 07:41 UTC by visigoth

This adds the `description` method to `NSObject`, which invokes the
`description` selector.

2020-12-30 07:42 UTC, visigoth commented
this adds a dependency between `objc` and `foundation` due to `NSString`, which if you really want to keep separate, needs to be compiled conditionally on whether the `foundation` feature is enabled. should this go in the `foundation` crate instead?

2020-12-30 08:00 UTC, nvzqz requested changes
Thanks for the contribution! I'm surprised I didn't have this already. 🙂

See my comment for what needs changing.

While you're at it, I think it would be good to also do `debugDescription`.

2020-12-30 08:00 UTC, nvzqz commented on src/objc/ns_object.rs
> +    pub fn description(&self) -> Arc<NSString> {
This should be behind the `foundation` feature flag, to not require `foundation` when only using `objc`.

I also try to link to Apple's original documentation when I can.

```suggestion
    ///
    /// See [documentation](https://developer.apple.com/documentation/objectivec/1418956-nsobject/1418746-description?language=objc).
    #[cfg(feature = "foundation")]
    #[inline]
    pub fn description(&self) -> Arc<crate::foundation::NSString> {
```

2021-01-10 01:53 UTC, visigoth commented on src/objc/ns_object.rs
> +    pub fn description(&self) -> Arc<NSString> {
alright, i made those changes. i mistakenly clobbered the original commit, but added new ones for the suggested changes. do you want me to build a commit history from the original PR commit, keep what's in the PR now, or should i squash before your merge?

2021-05-06 14:45 UTC, merged

2021-05-06 14:46 UTC, nvzqz commented
Thanks for the changes! Sorry it took me so long to get back to this. Expect a release with this within a week 🙂